### PR TITLE
Use admin_notices hook to display warning

### PR DESCRIPTION
**Pull request by barryceelen**
It appears the `install_plugins_pre_` hook is not meant to output HTML, hooking into `admin_notices` fixes that.

### CODE REVIEW

**Comment by helen** [comment]
Hi @barryceelen - sorry I neglected to respond to this PR for so long. I was never able to reproduce the PHP warning, and the current patch doesn't seem to actually display the notices for me. Maybe I'm looking in the wrong spot? If you could add some screenshots that might help. Thanks!

**Comment by barryceelen** [comment]
Hey @helen, thanks for getting back to this :-)
I can for the life of me not get it to generate the warning any more either, wish I had documented it ~better~ at all.

It might still be worthwhile to consider this update, as it uses the 'correct' hook for displaying the message. Also, using the core `notice notice-warning` classes negates the need for custom styles.

But that's me being nit-picky so feel free to ignore and I'll close this!

**Comment by helen** [comment]
Using a better hook and core classes would be awesome! I don't know why your current method doesn't work, I didn't dig in, but happy to explore it some more if you'd like.

**Comment by barryceelen** [comment]
Oh wait, it's not displaying for you on this branch? That's weird, seems to work as expected for me. Only thing it adds really is passing the display of the notice to the `admin_notices` hook.

pasted_image_04_08_18__01_38

**Comment by helen** [comment]
No, but I wonder if it's because I was testing in multisite. I'll try to take another look over the next few days.

**Comment by barryceelen** [comment]
Multisite uses `network_admin_notices`, which is why it wasn't showing up for you @helen, updated accordingly.

**Comment by helen** [comment]
Also a request here to change the base branch to develop :)

**Comment by barryceelen** [comment]
Done!

**Pull request merged**
