### PR TITLE
Introduce failsafe procedures for required options

### PR DESCRIPTION
**Pull request by christianc1**
In the event of a momentary database disconnection with WordPress, required options can be cached in `notoptions` and never re-checked upon database reconnection.  This pull request introduces filters that establish a failsafe procedure whereby required options can only exist in the `notoptions` cache for a maximum period, by default, 10 seconds.

### CODE REVIEW

**Comment by christianc1** [comment]
To test this feature, I simulated having a required option by adding it to the notoptions cache:
```php
$notoptions = wp_cache_get( 'notoptions', 'options' );
$notoptions['siteurl'] = true;
wp_cache_set( 'notoptions', $notoptions, 'options' );
```

Ensure this option is in the notoptions cache:
`wp cache get notoptions options`

> ```
> array (
>   ...
>   'siteurl' => true,
>   ...
> )
> ```

Attempt to retrieve the option:
`wp option get siteurl`
>`Error: Could not get 'siteurl' option. Does it exist?`

Wait 10s, attempt again:
`wp option get siteurl`
>`https://latest-wp.test`

Ensure this option is *NOT* in the notoptions cache:
`wp cache get notoptions options`

> ```
> array (
>   ...
> )
> ```

**Comment by tott** [comment]
This looks overall like a good approach. Thanks for doing this. 
I got two small things we should add
- add rewrite_rules to the list of options we recover
- also clear the option from alloptions to ensure it's not falsely cached

**Comment by christianc1** [comment]
@tott I added rewrite rules to the array of required rules.  Perhaps I'm missing something, but how would the value of an option become falsely cached in `alloptions`?

**Comment by tott** [comment]
> @tott I added rewrite rules to the array of required rules. Perhaps I'm missing something, but how would the value of an option become falsely cached in `alloptions`?

It could still have a value in alloptions cache from before but the notoptions fires before the alloptions check so i'd rather make sure it's unset before we do the get_option to really enforce that this call queries the db and does

**Comment by tlovett1** [comment]
@christianc1 this looks great. Thank you for putting it together.

I don't really know how to test this well, and if this code is wrong, it will break the site. Any ideas on testing?

**Comment by christianc1** [comment]
@tlovett1 , My testing methodology was added to this pull request as the [first comment](https://github.com/10up/10up-experience/pull/45#issuecomment-477434277).

**Comment by christianc1** [comment]
@tott :  Added logic to purge the "required option" where core caches the value.

**Comment by christianc1** [comment]
closing in favor of #46

**Pull request closed without merging**
